### ISSUE TITLE
exception error upon activating revolution slider 5.4

### ISSUE THREAD

**Issue by merc28** [stylus/nib#339]
Below is the copied error exception that WordPress returned after I installed and Activated revslider version 5.4.

I believe this has happened in the past with a previous version of revslider in Gantry 4. I think there is a simple solution such as enabling the mootools particle or some other setting in Gantry 5. 
Also, i'm using the very latest update of WordPress.

_This is the error prompt from WP:_

`Whoops\Exception\ErrorException thrown with message "Call to a member function get_url() on null"

Stacktrace:
#0 Whoops\Exception\ErrorException in /home7/laughix9/public_html/wp-content/plugins/revslider/includes/template.class.php:136
`

**Comment by vendethiel** [comment]
...How's that related to nib?&

**Comment by Panya** [comment]
Not related to nib.

**Comment by merc28** [comment]
Mikhail, may i ask you the purpose of this email?

On Sat, Mar 10, 2018 at 4:38 PM, Mikhail Korepanov <notifications@github.com

**Comment by Panya** [comment]
@merc28 you received this email because I commented and closed your issue as not related to nib (github send them automatically). See:
> You are receiving this because you authored the thread.
 Reply to this email directly, view it on GitHub
 <#339 (comment)>, or mute the
 thread
