### ISSUE TITLE
Is there any sucessor or anyone with an alternative to NIB?

### ISSUE THREAD

**Issue by acauamontiel** [stylus/nib#346]
It's been over 2 years since the last commit, so I'm looking for an alternative or someone who wants to collab on a new project.

**Comment by vendethiel** [comment]
I think the landscape has really changed in the past few years, Stylus or other CSS preprocs are not as often used, polyfills are not as important, and many features that CSS frameworks like nib or bourbon used to provide are easy to do with newer css versions.
