### ISSUE TITLE
Would someone please update the npm version?

### ISSUE THREAD

**Issue by mapxn** [stylus/nib#353]
Would you please update the lastest version on npm in convenience?
https://www.npmjs.com/package/nib
That'll very helpful.

**Comment by mapxn** [comment]
![image](https://user-images.githubusercontent.com/16299874/143544862-0781a6d0-b556-4070-acaf-bbead2f284a7.png)

**Comment by mapxn** [comment]
It seems like [npm](https://www.npmjs.com/package/nib) version was not the lastes version.

**Comment by mapxn** [comment]
@tj @notslang

**Comment by iChenLei** [comment]
@notslang Thanks, I accepted. But I still no permission to manage nib github repo, can you add me as nib repository ?

**Comment by notslang** [comment]
I don't think I have access to that. I can't even see the "Settings" tab on this repo. Maybe someone else in the stylus org can add you?

![1652712386](https://user-images.githubusercontent.com/1049204/168620373-72f564cb-be63-4759-9f87-580fd964bba1.png)

**Comment by iChenLei** [comment]
@notslang Ok, Thanks.

**Comment by MHuiG** [comment]
Of course there are other solutions, such as creating a new repository, or merging the nib and stylus management together
