### ISSUE TITLE
Release 1.1.3 with stylus dependency fixed

### ISSUE THREAD

**Issue by dresende** [stylus/nib#354]
@notslang released 1.1.2 on 27 Oct 2021 but this version has 5 years and dependency on stylus is broken.

I get a lot of errors that trace back to stylus dependency (0.54.5) inside nib, but if I force this dependency in shrinkwrap to 0.55.0 this disappears, so it's nothing with nib, just package.json (the one published by nib) that needs an update. On master branch, this has already been fixed, just need to be released in a new version.

/cc @tj

**Comment by mapxn** [comment]
This project looks like no one has maintained it.

**Comment by dresende** [comment]
Opened discussion [here](https://github.com/stylus/stylus/discussions/2670)
